spring.application.name=nori-sales
spring.datasource.url=jdbc:postgresql://localhost:5432/nori_sales
spring.datasource.username=postgres
spring.datasource.password=nori@2026
api.security.token.secret=5hXMXZ1voi9HWkoQWhTtuFt05KzuoJeL98mxjAgR3iX
# two hours
api.security.token.expiration=7200000

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

server.servlet.application-display-name=nori-sales