spring.application.name=nori-sales
server.servlet.application-display-name=nori-sales
server.servlet.context-path=/nori-sales/v1
spring.datasource.url=jdbc:postgresql://localhost:5432/nori_sales
spring.datasource.username=postgres
spring.datasource.password=nori@2026
api.security.token.secret=${JWT_SECRET}
api.security.token.expiration=${JWT_EXPIRATION}
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
mercadopago.access-token=${MERCADOPAGO_ACCESS_TOKEN}

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer