-- =============================================================
--  V6 — Table: payments
-- =============================================================

CREATE TABLE payments (
                          id              UUID            NOT NULL DEFAULT gen_random_uuid(),
                          order_id        UUID            NOT NULL,
                          status          VARCHAR(30)     NOT NULL DEFAULT 'PENDING',
                          method          VARCHAR(20)     NOT NULL DEFAULT 'PIX',
                          amount          NUMERIC(12, 2)  NOT NULL,
                          pix_qr_code     TEXT,
                          pix_qr_code_b64 TEXT,
                          external_id     VARCHAR(255),
                          paid_at         TIMESTAMP,
                          created_at      TIMESTAMP       NOT NULL DEFAULT NOW(),
                          updated_at      TIMESTAMP       NOT NULL DEFAULT NOW(),

                          CONSTRAINT pk_payments           PRIMARY KEY (id),
                          CONSTRAINT fk_payments_order     FOREIGN KEY (order_id) REFERENCES orders (id),
                          CONSTRAINT uq_payments_order     UNIQUE (order_id),
                          CONSTRAINT ck_payments_status    CHECK (status IN (
                                                                             'PENDING',
                                                                             'APPROVED',
                                                                             'DECLINED',
                                                                             'EXPIRED'
                              )),
                          CONSTRAINT ck_payments_method    CHECK (method IN ('PIX')),
                          CONSTRAINT ck_payments_amount    CHECK (amount > 0)
);

COMMENT ON TABLE  payments              IS 'Payments linked to orders — Mercado Pago sandbox integration';
COMMENT ON COLUMN payments.pix_qr_code  IS 'Copy-and-paste Pix code generated by Mercado Pago';
COMMENT ON COLUMN payments.pix_qr_code_b64 IS 'Base64 QR Code for rendering in the frontend';
COMMENT ON COLUMN payments.external_id  IS 'Payment ID returned by Mercado Pago';
COMMENT ON COLUMN payments.paid_at      IS 'Timestamp of payment confirmation';

CREATE INDEX idx_payments_order  ON payments (order_id);
CREATE INDEX idx_payments_status ON payments (status);